{
 "title": "Radix",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_epoch_num" }
   ]
  },
  {
   "title": "Node diff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rx_diff" }
   ]
  },
  {
   "title": "Current validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_total_current_validators" }
   ]
  },
  {
   "title": "Epoch progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rx_epoch_progress / 100000) * 100"
    }
   ]
  },
  {
   "title": "Next validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_total_next_validators" }
   ]
  },
  {
   "title": "Validator next",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_validator_next" }
   ]
  },
  {
   "title": "Validator Now",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_validator" }
   ]
  },
  {
   "title": "Signs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rx_epoch_sign", "legendFormat": "Signs" }
   ]
  },
  {
   "title": "TPS mem",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_tps_mem" }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_tps" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "RAM used "
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=~\"$job\"} / node_memory_SwapTotal_bytes{job=~\"$job\"})) * 100",
     "legendFormat": "SWAP used "
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=~\"$job\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk used"
    }
   ]
  }
 ]
}